org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.18
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=dream_eatery
mod_name=梦食坊 (Dream Eatery)
mod_license=All Rights Reserved
mod_version=1.0-SNAPSHOT
mod_group_id=org.lanye
mod_authors=lan_ye, MoonStarfish
mod_description=幻梦系列 · 美食与料理内容模组。需安装 Reverie Core 与 GeckoLib 前置模组。
geckolib_version=4.8.3
geckolib_version_range=[4.8.0,5.0)
