org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.18
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=dream_eatery
mod_name=\u68a6\u98df\u574a (Dream Eatery)
mod_license=All Rights Reserved
mod_version=1.0-SNAPSHOT
mod_group_id=org.lanye
mod_authors=lan_ye, MoonStarfish
mod_description=\u5e7b\u68a6\u7cfb\u5217 \u00b7 \u7f8e\u98df\u4e0e\u6599\u7406\u5185\u5bb9\u6a21\u7ec4\u3002\u9700\u5b89\u88c5 Reverie Core \u4e0e GeckoLib \u524d\u7f6e\u6a21\u7ec4\u3002
geckolib_version=4.8.3
geckolib_version_range=[4.8.0,5.0)
